default:
 colnames_config_read:
    - "script_dir"
    - "type"
    - "data_dir"
    - "base_data_dir"
    - "add_branch"
    - "extensions"
    - "message"
    - "notes"
 colnames_config_write:
    - "script_dir"
    - "type"
    - "data_dir"
    - "base_data_dir"
    - "add_branch"
    - "extension"
    - "message"
    - "notes"
